### ISSUE TITLE
User profileImage url를 카카오 cdn에서 얻어올 때 https링크로 얻어오기

### ISSUE THREAD

**Issue by manudeli** [slamapp/server#1]
## 내용
현재 profileImage로 http로 받고 있습니다
아마 http로 user에 profileImage로 저장되고 있는 것으로 보여요

### 변경 전
http://k.kakaocdn.net/dn/k8AUi/btreoEKvP1M/vckoclcNHsqks2ygyWyRNK/img_640x640.jpg

### 변경 전
https://k.kakaocdn.net/dn/k8AUi/btreoEKvP1M/vckoclcNHsqks2ygyWyRNK/img_640x640.jpg

**Comment by KwonYeKyeong** [comment]
첫 로그인, 즉 회원가입 시 카카오에서 이미지 링크를 받아오면 받아온 링크자체를 곧바로 db에 저장하고 있습니다. 그래서 프론트에 http로 내려지는 것 같네요. 카카오에서 받아온 이미지를 저희 s3에 저장해서 보내주도록 리팩토링해보겠습니다!!
(늦은 코멘트 죄송합니다ㅠㅠ)

**Comment by manudeli** [comment]
> 첫 로그인, 즉 회원가입 시 카카오에서 이미지 링크를 받아오면 받아온 링크자체를 곧바로 db에 저장하고 있습니다. 그래서 프론트에 http로 내려지는 것 같네요. 카카오에서 받아온 이미지를 저희 s3에 저장해서 보내주도록 리팩토링해보겠습니다!!
> (늦은 코멘트 죄송합니다ㅠㅠ)

제 생각에는 s3의 용량제한을 아끼기 위해서 위 예시처럼 http인 경우 https로 변환해서 response로 주는 로직만 작성하는 것도 방법일 것 같아요. 위 http, https 링크 둘 다 잘 동작은 하거든요

젤리는 어떠세요?

**Comment by KwonYeKyeong** [comment]
마누 현재 http로도 이미지 불러오는 작업이 잘되는데 https로 바꾸려는 이유를 정확히 할 수 있을까요?? 변경을 반대하는게 아니라 그냥 궁금해서 그렇습니다~~!! 
현재 클라이어튼와 서버가 https로 통신하고 있기 때문에 통일해주기 위해서정도인가요, 아님 이유가 더 있는건가요??

**Comment by manudeli** [comment]
🔗 http와 https의 보안적인 차이를 적어놓은 글이 있어서 공유해요

https://blog.wishket.com/http-vs-https-%EC%B0%A8%EC%9D%B4-%EC%95%8C%EB%A9%B4-%EC%82%AC%EC%9D%B4%ED%8A%B8%EC%9D%98-%EB%A0%88%EB%B2%A8%EC%9D%B4-%EB%B3%B4%EC%9D%B8%EB%8B%A4/

다른 방법으로는 클라이언트 측에서 주소가 http인 경우에 https로 요청하도록 변환할 수도 있긴 할 것 같은데 db에서 미리 https로 저장했다면 클라이언트 측에서 산재된 곳에서 https로 변환해줄 필요가 없고 더 효율적이라고 생각해서 이미지링크를 저장할 때 https로 저장되도록 백엔드에 요청 드렸어요
