### ISSUE TITLE
[User] 간헐적인 카카오로그인 whitelabel 에러 -> email 수집 철회

### ISSUE THREAD

**Issue by manudeli** [slamapp/server#73]
![1665491210336](https://user-images.githubusercontent.com/61593290/195090197-151378eb-9f22-4dbd-89a2-f54190774fc8.jpg)

**Comment by KwonYeKyeong** [comment]
화이트라벨 에러(위 에러) : 회원가입시 이메일 제공 동의여부가 선택으로 되어있어서 동의제공을 하지 않게 되면 발생하는 에러
-> 해결방법 : 서비스를 비즈앱으로 승격 후 이메일 필수동의로 변경[참고](https://devtalk.kakao.com/t/topic/106952)

**Comment by manudeli** [comment]
반대로 이메일 정보 제공을 하지 않도록 할 수는 없을까요?
지금 보면 동의 안해도 white label이 뜨기는 하지만 로그인은 되더라구요
이메일이 불필요한 상황인거 같아서 필수동의보다는 email 수집을 안하는 쪽은 어떠신가요?

로그인하시고 여기서 수정할 수 있어요~
https://developers.kakao.com/console/app/672903/product/login/scope

<img width="1755" alt="image" src="https://user-images.githubusercontent.com/61593290/197506165-ba98fe2d-fc04-4b02-959d-21c8e33829a7.png">

**Comment by manudeli** [comment]
처음엔 화이트라벨뜨고 새로고침하면 로그인되더라구요~

**Comment by KwonYeKyeong** [comment]
그리고 서비스를 비즈앱으로 승격시키기 위해서는 서비스의 owner만 가능하네요 그리고 그 owner가 지금은 마누로 되어있어서 제가 직접 비즈앱으로 승격을 못 시키는 상황입니다. 이메일 수집에 관해서 이번주 회의 때 얘기해봐도 될 것 같네요~

**Comment by KwonYeKyeong** [comment]
> 처음엔 화이트라벨뜨고 새로고침하면 로그인되더라구요~
> 
> 그럼 젤리 이메일을 필수로 하려면 비즈앱 승격이 필요한데 사업자등록증이 필요하더라구요 개인앱의 경우도 나중에 필요하던데 가능한걸까요?
> 
> 다른 방법으로는 이메일을 선택사항으로 남기고 이메일 제공울 동의하지 않더라도 가입되게 할 수 있지 않을까요?

제가 본 방법은 [사업자 번호 없이 비즈앱 설정](https://devtalk.kakao.com/t/how-can-i-switch-to-a-biz-app-if-i-do-not-have-any-business-registration-number/71983?source_topic_id=106952) 이거였어요...!!

**Comment by manudeli** [comment]
> 그리고 서비스를 비즈앱으로 승격시키기 위해서는 서비스의 owner만 가능하네요 그리고 그 owner가 지금은 마누로 되어있어서 제가 직접 비즈앱으로 승격을 못 시키는 상황입니다. 이메일 수집에 관해서 이번주 회의 때 얘기해봐도 될 것 같네요~

젤리가 직접 비즈앱으로 올리자는 게 아니고 비즈앱으로 올리려면 사업자등록증이 필요하다는 이야기에요~ 근데 사업자등록증을 발급받아서 이메일을 받는 게 좋은 선택인지는 와닿지 않아서요~ 어쨌든 개인정보를 수집하게 되면 개인정보가 유출되었을 때에 대한 책임을 져야할텐데 그 책임을 질만한 정도로 이메일이 필요한 건지 이유를 좀 더 설명해주시면 좋을 거 같아요

사업자등록증을 받기 전까지는 선택사항으로 받을 수 밖에 없는 상황으로 보여서요 그런데 저희 사업자등록증을 발급받을 건가요?
